### ISSUE TITLE
Pip install does not seem functional

### ISSUE THREAD

**Issue by pholur** [chanind/frame-semantic-transformer#20]
I am trying to use the `pip` installation but could not find a matching distribution. Can the authors confirm if this pipeline works?

**Comment by chanind** [comment]
What is the specific error you're getting and on what platform? Did you run `pip install frame-semantic-transformer`? Here is a simple colab which installs the library via pip: https://colab.research.google.com/drive/15BGyGsc7V0Qbm3tPYInv1lozW1YZ_3_3?usp=sharing.

**Comment by pholur** [comment]
Thanks! Weird it's working now for some reason.
